kind: pipeline
type: docker
name: php

steps:
- name: composer build
  image: composer
  commands:
    - cd src/
    - composer install --ignore-platform-reqs
  volumes:
    - name: php-cache
      path: /drone/src/src/vendor

- name: yarn build
  image: node:16-alpine
  commands:
    - cd src/
    - yarn install
    - yarn run dev

- name: lint
  image: php:8
  commands:
    - cd src/
    - vendor/bin/phpcs --colors -p  src/ tests/
    - vendor/bin/phpstan analyse

- name: test
  image: php:8
  commands:
    - cd src/
    - vendor/bin/phpunit tests/

---
kind: pipeline
type: docker
name: vue

steps:
- name: build
  image: node:16-alpine
  commands:
    - cd src/
    - yarn install
  volumes:
    - name: vue-cache
      path: /drone/src/src/node_modules
