version: '3.8'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.dev
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: door-maintainer-application
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    ports:
      - '9000:9000'
    depends_on:
      - database
    links:
      - database
    networks:
      - door-maintainer

  cake:
    build:
      context: ./docker/cli
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: door-maintainer-cli
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    entrypoint: bin/cake
    networks:
      - door-maintainer

  nginx:
    image: nginx:stable-alpine
    container_name: door-maintainer-nginx
    ports:
      - '4000:80'
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - door-maintainer

  yarn:
    image: node:${NODE_VERSION}-alpine
    container_name: ${PROJECT_NAME}-yarn
    env_file: .env
    entrypoint: yarn
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - door-maintainer

  asset-mix:
    image: node:${NODE_VERSION}-alpine
    container_name: ${PROJECT_NAME}-asset-mix
    env_file: .env
    command: run watch
    entrypoint: yarn
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - door-maintainer

  database:
    image: mysql:8
    container_name: door-maintainer-database
    ports:
      - '3306:3306'
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - door-maintainer-data:/var/lib/mysql
    networks:
      - door-maintainer

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: door-maintainer-admin
    depends_on:
      - database
    environment:
      PMA_HOST: database
    ports:
      - '4004:80'
    links:
      - database
    networks:
      - door-maintainer

networks:
  door-maintainer:

volumes:
  door-maintainer-data:
