version: '3.8'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.dev
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: door-maintainer-application
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    ports:
      - '9000:9000'
    depends_on:
      - database
    links:
      - database
    networks:
      - door-maintainer

  door-maintainer:
    build:
      context: ./docker/cli
      dockerfile: Dockerfile
      args:
        PHP_CLI_VERSION: ${PHP_CLI_VERSION}
    container_name: door-maintainer-cli
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    entrypoint: bin/cake
    networks:
      - door-maintainer

  nginx:
    image: nginx:stable-alpine
    container_name: door-maintainer-nginx
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - door-maintainer

  yarn:
    container_name: door-maintainer-yarn
    build:
      context: ./src
      dockerfile: ../docker/yarn/Dockerfile
    volumes:
      - ./src:/app
    networks:
      - door-maintainer

  assetmix:
    container_name: door-maintainer-assetmix
    build:
      context: ./src
      dockerfile: ../docker/yarn/Dockerfile
    command: run watch
    volumes:
      - ./src:/app
    depends_on:
      - php
    networks:
      - door-maintainer

  database:
    image: mysql:8
    container_name: door-maintainer-database
    ports:
      - '3306:3306'
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - door-maintainer-data:/var/lib/mysql
    networks:
      - door-maintainer

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: door-maintainer-admin
    depends_on:
      - database
    environment:
      PMA_HOST: database
    ports:
      - '8884:80'
    links:
      - database
    networks:
      - door-maintainer

networks:
  door-maintainer:

volumes:
  door-maintainer-data:
